version: '2'

services:
  quiz-db:
    image: mysql:5.7
    container_name: quiz-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=quiz
      - MYSQL_DATABASE=quiz
      - MYSQL_USER=quiz
      - MYSQL_PASSWORD=quiz
    ports:
      - "3306:3306"
  quiz-app:
    build: .
    container_name: quiz-app
    depends_on:
      - quiz-db
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"